### ISSUE TITLE
Calculated Shipping Rates in BUY SDK inconsistently causing crash

### ISSUE THREAD

**Issue by MrGobert** [Shopify/mobile-buy-sdk-ios#612] opened 2017-05-31 02:50 UTC
Whenever I use the call `getShippingRatesForCheckout(withToken:)` the app crashes to app delegate. No output or error returns. This only occurs when my shipping zone is set to calculated rates (USPS). If I use weight based, or price based everything works fine. 

I found an issue from 2015 that complained about the exact same thing but was later closed as fixed. It doesn't even appear to be a per store issue. Other stores we've created are crashing for some products and not others. Not sure if its a Shopify API issue or an issue with USPS. If anyone has any insight on this I would be very grateful.

**Comment by mobass11** [comment] 2017-05-31 04:04
This issue is also affecting my app. Please help

**Comment by EricNetsch** [comment] 2017-05-31 04:05
I am getting the same issue on my app using the getShippingRatesForCheckout(withToken:)
No errors are being presented and the app is crashing unexpectedly. It seems to be related to dynamic shipping rates @fananta @skanwar  @tobi  @bgulanowski

**Comment by fananta** [comment] 2017-05-31 04:27
Thanks for logging this, we'll look into this asap.

**Comment by bgulanowski** [comment] 2017-05-31 13:12
Please provide a backtrace with all crash reports. We need to know where the exception happened.

If you haven't done so, please add an exception breakpoint in Xcode.

Please see **[Debugging with Xcode](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/debugging_tools.html#//apple_ref/doc/uid/TP40015022-CH8-SW3)** for more information on breakpoints.

**Comment by EricNetsch** [comment] 2017-05-31 18:13
@fananta @bgulanowski  
This is definitely an issue with changes made to the Shipping rates API.
The crash is happening when the shipping rates json is passed to the model manager
`
shippingRates = [self.modelManager insertShippingRatesWithJSONArray: json[@"shipping_rates"]];`

`The exact crash is happens here: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
`
The Shipping rates returning from the API but are unable to be converted into BUYShippingRate objects using the model manager.

This is crashing affecting all Shopify stores using USPS calculated shipping rates.

**Comment by fananta** [comment] 2017-05-31 21:05
Can you provide a full stack trace @ericnetsch

**Comment by EricNetsch** [comment] 2017-05-31 21:27
@fananta @bgulanowski 
```
2017-05-31 14:18:02.654 Tapcart[78674:11478310] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107ce5b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107335141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000107c1a4a3 -[__NSArrayM insertObject:atIndex:] + 1603
	3   Buy                                 0x000000010668530b __33-[NSArray(BUYAdditions) buy_map:]_block_invoke + 139
	4   CoreFoundation                      0x0000000107c77e4d __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 77
	5   CoreFoundation                      0x0000000107c77d06 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 166
	6   Buy                                 0x0000000106685210 -[NSArray(BUYAdditions) buy_map:] + 288
	7   Buy                                 0x0000000106677f94 -[BUYDeliveryRangeTransformer reverseTransformedValue:] + 196
	8   Buy                                 0x0000000106688fc2 -[NSAttributeDescription(BUYAdditions) buy_valueForJSON:object:] + 162
	9   Buy                                 0x00000001066883ea __63-[NSEntityDescription(BUYAdditions) buy_updateObject:withJSON:]_block_invoke + 298
	10  CoreFoundation                      0x0000000107c779ae __65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 94
	11  CoreFoundation                      0x0000000107c778ba -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 234
	12  Buy                                 0x00000001066881e6 -[NSEntityDescription(BUYAdditions) buy_updateObject:withJSON:] + 854
	13  Buy                                 0x000000010667d3a0 -[BUYObject setJSONDictionary:] + 144
	14  Buy                                 0x000000010667d0f0 -[BUYObject initWithModelManager:JSONDictionary:] + 176
	15  Buy                                 0x000000010667c6b4 __55-[BUYModelManager buy_objectsWithEntityName:JSONArray:]_block_invoke + 100
	16  Buy                                 0x00000001066852e9 __33-[NSArray(BUYAdditions) buy_map:]_block_invoke + 105
	17  CoreFoundation                      0x0000000107c77e4d __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 77
	18  CoreFoundation                      0x0000000107c77d06 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 166
	19  Buy                                 0x0000000106685210 -[NSArray(BUYAdditions) buy_map:] + 288
	20  Buy                                 0x000000010667c5d9 -[BUYModelManager buy_objectsWithEntityName:JSONArray:] + 361
	21  Buy                                 0x0000000106653ffa -[BUYModelManager(BUYShippingRateInserting) insertShippingRatesWithJSONArray:] + 74
	22  Buy                                 0x00000001066684fd __71-[BUYClient(Checkout) getShippingRatesForCheckoutWithToken:completion:]_block_invoke + 269
	23  Buy                                 0x00000001066753d4 __65-[BUYClient requestForURL:method:object:start:completionHandler:]_block_invoke_2 + 52
	24  Foundation                          0x0000000106e3f237 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	25  Foundation                          0x0000000106e3ef3b -[NSBlockOperation main] + 101
	26  Foundation                          0x0000000106e3d6f7 -[__NSOperationInternal _start:] + 627
	27  Foundation                          0x0000000106e3947c __NSOQSchedule_f + 198
	28  libdispatch.dylib                   0x000000010b48c05c _dispatch_client_callout + 8
	29  libdispatch.dylib                   0x000000010b46d40b _dispatch_main_queue_callback_4CF + 411
	30  CoreFoundation                      0x0000000107caa909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	31  CoreFoundation                      0x0000000107c70ae4 __CFRunLoopRun + 2164
	32  CoreFoundation                      0x0000000107c70016 CFRunLoopRunSpecific + 406
	33  GraphicsServices                    0x000000010ce22a24 GSEventRunModal + 62
	34  UIKit                               0x000000010965c0d4 UIApplicationMain + 159
	35  Tapcart                             0x0000000106068f67 main + 55
	36  libdyld.dylib                       0x000000010b4d865d start + 1
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

<img width="567" alt="screenshot 2017-05-31 14 25 36" src="https://cloud.githubusercontent.com/assets/5900690/26654861/3386d0f2-460d-11e7-81f6-4edf2b65fca5.png">

**Comment by bgulanowski** [comment] 2017-05-31 22:55
Is this happening with Apple Pay? or a custom native checkout? Is the shop using Shopify Payments?

I cannot reproduce with Apple Pay.

Can you provide the actual response from Shopify that you are getting instead of shipping rates? Is it just empty? No error, I assume, because if there was, we wouldn't try to create the shipping rates models.

**Comment by bgulanowski** [comment] 2017-05-31 23:09
To provide some context, the exception appears to be caused by the fact that where we are expecting a delivery date range, we are getting something else. Possibly the format for delivery dates was modified.

**Comment by MrGobert** [comment] 2017-05-31 23:29
This was our suspicion. Is this something that can be fixed from their end, Shopify's API or the Buy SDK? And is there an ETA for the fix? More than half of our customers use the calculated shipping rate and their apps are currently crashing whenever someone tries to make a purchase. Thanks for your help with this!

**Comment by EricNetsch** [comment] 2017-05-31 23:51
I found a fix. Shopify changed the date range values in the API to be an array instead of a string. This broke every app using the SDK when shipping ranges are returned as an array. I am setting the value to nil now in the ValueTransformer function and everything works fine. Im happy to help with any issues or fixes regarding this. let's patch this up and move forward with real fix so we can update all our apps as soon as possible. 

```
- (NSArray *)reverseTransformedValue:(NSArray *)value
{
    value = nil;
    
	NSValueTransformer *ValueTransformer = [NSValueTransformer valueTransformerForName:BUYShippingRateDateTransformerName];
	return [value buy_map:^(NSString *dateString) {
		return [dateTransformer reverseTransformedValue:dateString];
	}];
}
```

**Comment by bgulanowski** [comment] 2017-06-01 00:12
I am trying to track down where that data comes from, but it's taking a bit of time. I'm a mobile dev not a Rails dev, and it's now well after hours in Toronto. I should be able to find the code change and will request a fix from the team. Thanks for your patience.

**Comment by bgulanowski** [comment] 2017-06-01 00:44
@EricNetsch  It would help a lot to have the exact JSON response body, if you can get it. if you can break inside the completion block in `BuyClient+Checkout#getShippingRates()`, you can convert the responseData on the NSHTTPURLResponse object (may have to climb up the stack a bit) to a string with something like `po [NSString stringWithData:responseData encoding:4]` (where `4` means `UTF8StringEncoding`).

**Comment by EricNetsch** [comment] 2017-06-01 00:50
@bgulanowski 
Ok great. Here it is for one of our apps:
```
"shipping_rates" =     (
                {
            checkout =             {
                "subtotal_price" = "30.00";
                "total_price" = "37.88";
                "total_tax" = "2.56";
            };
            "delivery_range" =             (
                "2017-06-02",
                "2017-06-02"
            );
            id = "usps-FirstPackage-5.32";
            "phone_required" = 0;
            price = "5.32";
            title = "First Class Package";
        },
                {
            checkout =             {
                "subtotal_price" = "30.00";
                "total_price" = "41.85";
                "total_tax" = "2.83";
            };
            "delivery_range" =             (
                "2017-06-02",
                "2017-06-02"
            );
            id = "usps-Priority-9.02";
            "phone_required" = 0;
            price = "9.02";
            title = "Priority Mail";
        },
                {
            checkout =             {
                "subtotal_price" = "30.00";
                "total_price" = "62.85";
                "total_tax" = "4.25";
            };
            "delivery_range" =             (
                "2017-06-01",
                "2017-06-01"
            );
            id = "usps-PriorityExpress-28.60";
            "phone_required" = 0;
            price = "28.60";
            title = "Priority Mail Express";
        }
    );
```

**Comment by bgulanowski** [comment] 2017-06-01 00:56
It looks like the date formatting was updated as a side effect of updating another dependency. It dropped the hours/min/secs etc that used to be there, and NSDateFormatter (used in the data transformer) isn't flexible. We're looking at a fix to convert the date string back to the original format.

**Comment by bgulanowski** [comment] 2017-06-01 01:09
We know the exact cause now, and are working on a fix. It's not clear how long it will take, but I would expect it tomorrow some time. Very sorry for the trouble.

**Comment by bgulanowski** [comment] 2017-06-01 01:11
We should also fix the `-buy_map:` method to replace `nil` values with `NSNull` values.

**Comment by EricNetsch** [comment] 2017-06-01 01:15
Thanks @bgulanowski Looking forward to the fix and definitely ready to move on to the SDK 3.0 soon :) Let me know if you need anything else.

**Comment by bgulanowski** [comment] 2017-06-01 02:00
Good news! A fix has been merged. The original date string formatting has been restored. Please confirm when you get a chance.

**Comment by EricNetsch** [comment] 2017-06-01 03:59
@bgulanowski 
Great, thanks! Just to confirm, this change was made on the API side?
If API when will the code be deployed?

**Comment by bgulanowski** [comment] 2017-06-01 11:09
It was deployed automatically. I'm told it takes about 20 minutes for a merge to go live, so it was live last night at 10:30 EDT.

**Comment by fananta** [comment] 2017-06-01 16:40
Confirmed, this is fixed.

**Closed by fananta** 2017-06-01 16:40 UTC
