### ISSUE TITLE
Search products.

### ISSUE THREAD

**Issue by Brekhunchenko** [Shopify/mobile-buy-sdk-ios#294] opened 2016-08-11 10:23 UTC
Hi :)
Is there any way I can make search functionality in the app? 
Search through all products with specific title, for example.

**Comment by davidmuzi** [comment] 2016-08-11 13:07
Duplicate of #257

**Closed by davidmuzi** 2016-08-11 13:07 UTC

**Comment by Brekhunchenko** [comment] 2016-08-11 16:48
Thank you for response!
If there is no search implementation now, should my team and I expect this feature in next commit/release? 
Currently it is no way to implement search even without ios-sdk, am I right?

**Comment by davidmuzi** [comment] 2016-08-11 16:59
Search is not currently planned.

You could persist the product catalog on device, and perform search locally.

**Comment by kmrashish** [comment] 2016-09-09 07:13
One possible solution could be: Keep a mapping of product tags and your most relevant keywords, perform substring matching on keywords as the user types in for search, and then call the getProductsPage method with the tags corresponding to the keyword as the withTags argument. This should be done for the collection having all of your products.
