### ISSUE TITLE
Web checkout customer authorization

### ISSUE THREAD

**Issue by davidcorbin** [Shopify/mobile-buy-sdk-ios#882] opened 2018-07-07 15:42 UTC
Is there a way to authorize a customer so that they are logged in through the checkout website when it opens? I have the customer access token which would be used if the checkout were done in the app. It would save the user time and frustration if they were logged in already when the web page opened.

I’ve looked around and can’t find any documentation about this. Thank you for your help!

**Comment by dbart01** [comment] 2018-07-09 14:04
Closing as duplicate of #841.

**Closed by dbart01** 2018-07-09 14:04 UTC
Labels: duplicate
