### ISSUE TITLE
unable to get  multiple product Variant detail from VariantIds

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#902] opened 2018-08-16 10:16 UTC
hello

i want to display product available status  in cart page. so i am trying to get cart item product variant details in single query.
so unable to get multiple variant detail  from variant IDs

my query is here

```swift
 var ids = [GraphQL.ID]()
 ids.append(GraphQL.ID(rawValue: "variantID"))
 let query = Storefront.buildQuery { $0
            .nodes(ids: ids) { $0
                .onProductVariant
                {
                    $0.id()
                    .availableForSale()
                }
            }
        }
```

**Comment by dbart01** [comment] 2018-08-16 10:57
Where are you getting the value of "variantID"? It should be an opaque GraphQL ID, **_not_** a numeric variant ID. Is there a reason you need fetch `availableForSale` separate from the contents of your variants? Why not do it in a single request?

**Comment by networld301ios** [comment] 2018-08-16 13:43
getting variantID from my cart database. i passed a array of  GraphQL ID.

**Comment by dbart01** [comment] 2018-08-16 14:34
Can you please be more clear about what the problem is? What is the expected behaviour, what are you experiencing, etc. Is this an SDK issue or logic within your application?

**Comment by networld301ios** [comment] 2018-08-21 05:59
can i get all  variantdetail from variantID array

**Comment by dbart01** [comment] 2018-08-21 11:08
It doesn't appear to be an issue with the SDK. Closing, not enough information provided.

**Closed by dbart01** 2018-08-21 11:08 UTC
Labels: 3.x, question
