### ISSUE TITLE
isApplePayAvailable loses state on memory warning

### ISSUE THREAD

**Issue by bmgdev** [Shopify/mobile-buy-sdk-ios#87] opened 2016-01-15 09:06 UTC
I'm integrating Shopify for a sizable client of ours.   I spoke with a shopify engineer around a month ago by phone on this issue but he was still new on the iOS team and wasn't able to answer this issue...

What happens is, the bool, isApplePayAvailable, loses state when a memory issue occurs.  Why is this bad? Once isApplePayAvailable is set to 0 and the button reverts to "Set up apple pay", the user is taken to the credit card setup every time.  Somehow, [PKPaymentAuthorizationViewController canMakePayments] becomes unset.  

NOTE: BOOL didIntegrationSucceed = [client testIntegrationWithMerchantId:MERCHANT_ID]; will always return true even with the memory issue.  No issues there.

Does anyone have any insight? Im about to ditch Shopify for the client if I cant figure this out.  The issue has been around for the past 3 releases now (3 months?).

**Comment by bgulanowski** [comment] 2016-01-15 18:42
Apologies if this nitpicking, but `isApplePayAvailable` is a derived property, so it can't ever be "set to 0", although it can return `FALSE`. It doesn't make sense to focus on that method, specifically because it is derived. In order to help track this down, we would have to know which of the underlying properties changed.

As a reminder, here is the implementation:

```objective-c
- (BOOL)isApplePayAvailable
{
	// checks if the client is setup to use Apple Pay
	// checks if device hardware is capable of using Apple Pay
	// checks if the device has a payment card setup
	return (self.merchantId.length &&
			[PKPaymentAuthorizationViewController canMakePayments] &&
			[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]);
}
```

Therefore, at least one of these three checks has to return `0`/`NO`. (Strictly, the first check should be `self.merchantId.length > 0`.) As I suggested when we spoke, you will need to determine which of these three checks has changed its value.

If the merchantId has changed, I don't see how the SDK could be responsible, but perhaps there is an edge case where it gets reset.

The second check is fully controlled by the Apple Pay framework.

The third check relies on both Apple Pay and the SDK. If `self.supportedNetworks` returns `nil`, or garbage, that would be a problem.

Please let us know which of these checks is changing its value.

The SDK does not listen for or respond to memory pressure warning notifications. Therefore, it's very difficult to image how the SDK would be responsible for the return value of `-isApplePayAvailable` changing without warning.

My suspicion is that there is a memory-related error somewhere (although it seems unlikely it is in the SDK, for the aforementioned reason), and it is causing garbage data to overwrite either the merchantId property, or the `supportedNetworks` property. So I'd check with those first. Since those properties are the client application's responsibility, I'm not sure how we can help you confirm that they are still valid.

My recommendation is that you enable the memory-related diagnostic options in your app when debugging. If you aren't familiar with them, they are available from the target's scheme, under the Run action, on the Diagnostics tab, as in the screenshot:

![xcode diagnostic options](https://cloud.githubusercontent.com/assets/186680/12361697/9b970e48-bb8d-11e5-9ba6-dd827fdf86da.png)

In future, if you are filing bug reports, please provide steps to reproduce your problem, ideally with sample code. Otherwise, we are forced to try to guess what might be wrong. As we have never encountered this problem internally, we are unable to confidently determine the problem. Fortunately, as this is open source code, you should be able to easily identify the root cause of the problem.

Let us know if you make any further progress. Thanks.

**Comment by bmgdev** [comment] 2016-01-15 19:08
Apologies, I will be more explicit in my response.  I wasn't sure how deeply I should dive here given my responses from the team in the past.  Am happy to meet someone on the team with a deeper level of understanding in the SDK so thank you immensely!  I can't express enough how thankful I am for the response.

So yes, exactly, self.supportedNetworks returns 0 on memory pressure.

-------------------------
Remove this call once integration succeeds.  This should never be called in production code!!
Integration successful? YES
self.merchantId.length: 20
[PKPaymentAuthorizationViewController canMakePayments]: 1
[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 1
-------------------------
Received memory warning.
memory warning NativeShop
Remove this call once integration succeeds.  This should never be called in production code!!
Integration successful? YES
self.merchantId.length: 20
[PKPaymentAuthorizationViewController canMakePayments]: 1
[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 0
-------------------------

I've, of course, profiled the app until the cows came home. No luck in determining why self.supportedNetworks goes to 0 in my profiling tests.

Fortunately, this is open source code which should be very easy for me to debug. Unfortunately, its completely unapparent why self.supportedNetworks goes 0 on memory pressure.  I dont see how this is something that would be controlled in anything outside of the SDK.  

Any further insight or direction would be greatly appreciated.  Again, thank you for your timely response!  Really great of you.

**Comment by bmgdev** [comment] 2016-01-15 19:10
Apologies, I will be more explicit in my response.  I wasn't sure how deeply I should dive here given my responses from the team in the past.  Am happy to meet someone on the team with a deeper level of understanding in the SDK so thank you immensely!  I can't express enough how thankful I am for the response.

So yes, exactly, self.supportedNetworks returns 0 on memory pressure.


	-------------------------
	Remove this call once integration succeeds.  This should never be called in production code!!
	Integration successful? YES
	self.merchantId.length: 20
	[PKPaymentAuthorizationViewController canMakePayments]: 1
	[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 1
	-------------------------
	Received memory warning.
	memory warning NativeShop
	Remove this call once integration succeeds.  This should never be called in production code!!
	Integration successful? YES
	self.merchantId.length: 20
	[PKPaymentAuthorizationViewController canMakePayments]: 1
	[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 0
	-------------------------


I've, of course, profiled the app until the cows came home. No luck in determining why self.supportedNetworks goes to 0 in my profiling tests.

Fortunately, this is open source code which should be very easy for me to debug. Unfortunately, its completely unapparent why self.supportedNetworks goes 0 on memory pressure.  I dont see how this is something that would be controlled in anything outside of the SDK.  

Any further insight or direction would be greatly appreciated.  Again, thank you for your timely response!  Really great of you.

**Comment by bgulanowski** [comment] 2016-01-15 19:26
`BUYViewController.supportedNetworks` is an `NSArray`. If it's returning `nil`, then something is setting it to `nil`, or, more likely, it is never being set in the first place. Does the view controller get released and recreated? Could there be an alternate code flow where it is recreated but the property is not correctly initialized?

**Comment by bgulanowski** [comment] 2016-01-15 20:03
The only place we seem to set the value of `supportedNetworks` is here, in `BUYViewController.m`:

```objective-c
- (void)setClient:(BUYClient *)client
{
	_client = client;
	if (&PKPaymentNetworkDiscover != NULL) {
		self.supportedNetworks = @[PKPaymentNetworkAmex, PKPaymentNetworkMasterCard, PKPaymentNetworkVisa, PKPaymentNetworkDiscover];
	} else {
		self.supportedNetworks = @[PKPaymentNetworkAmex, PKPaymentNetworkMasterCard, PKPaymentNetworkVisa];
	}
}
```
I can't find anyplace that we are setting it to `nil` in the repo. It is set as a side effect of creating a `BUYViewController`. If an instance of `BUYViewController` is instantiated without a `BUYClient`, then `-setClient:` will not be called, and the `supportedNetworks` property will be `nil`. So I would look for any place where the `client` argument to `-initWithClient:` is `nil` (`BUYViewController.init` is declared unavailable, so I don't think that's the source.)

**Comment by bmgdev** [comment] 2016-01-15 20:13
The interesting part is, supportedNetworks is never squashed, it never goes nil, so setClient is doing the right thing.  So when passing in self.supportedNetworks to [PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks, it starts throwing nil on memory issue, see below:

	-------------------------
	Remove this call once integration succeeds.  This should never be called in production code!!
	Integration successful? YES
	self.merchantId.length: 20
	[PKPaymentAuthorizationViewController canMakePayments]: 1
	[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 1
	self.supportedNetworks: (
	    AmEx,
	    MasterCard,
	    Visa,
	    Discover
	)
	-------------------------
	Received memory warning.
	memory warning NativeShop
	Remove this call once integration succeeds.  This should never be called in production code!!
	Integration successful? YES
	self.merchantId.length: 20
	[PKPaymentAuthorizationViewController canMakePayments]: 1
	[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]: 0
	self.supportedNetworks: (
	    AmEx,
	    MasterCard,
	    Visa,
	    Discover
	)
	-------------------------

Strange?

**Comment by bgulanowski** [comment] 2016-01-15 22:35
It seems strange to me.

The docs say "If there are no configured payment cards, this method always returns NO." But it seems unlikely that the configured card could suddenly get lost. " `PKPaymentAuthorizationViewController` is unhappy about something, but I am at a loss as to what that might be.

I have asked the rest of the team to consider what else might affect the behaviour of this class, but we're limited by what the Apple documentation tells us.

**Comment by runmad** [comment] 2016-01-15 23:15
I'm curious, are you testing this with the simulator or on a device with Apple Pay?

There might be an issue with the Simulator.

Also, I think it's worth isolating to see whether it happens in an environment outside of the SDK to determine where the issue lies.

**Comment by bmgdev** [comment] 2016-01-15 23:33
This can only be reproduced on device.  Simulating memory warning through interface and programmatically doesnt seem to work in Simulator.  All is fine in Simulator.

I'm creating a test app now to try and reproduce out of the environment like you suggest, my only option at this point.  Its important to note, I can reproduce this issue in your 'Sample App Advanced' app as this is where I leveraged from.

**Comment by davidmuzi** [comment] 2016-01-19 20:36
If you can provide exact steps to reproduce the issue from our sample app, we will be able to triage the issue.

**Comment by bmgdev** [comment] 2016-01-19 21:54
The scrollback above are the exact steps.

**Comment by davidmuzi** [comment] 2016-01-19 22:10
Unfortunately, we cannot reproduce the issue here (causing the memory warning on device).  Can you try editing the supportedNetworks array, or just passing in an array literal @[PKPaymentNetworkVisa] to see where it breaks?  Keep adding the networks until it breaks.

Does this issue occur in a project without the Mobile Buy SDK?  It seems the only contribution from the SDK is the supportedNetworks array.  It appears the issue may be within PKPaymentAuthorizationViewController, and if so, a Radar should be created.

**Comment by runmad** [comment] 2016-01-25 15:00
@bmgdev Did you have a chance to test by passing in an array instead of using the `supportedNetworks` property?

**Comment by davidmuzi** [comment] 2016-01-29 20:56
Will close this ticket.  @bmgdev, let us know if you have additional info

**Comment by bmgdev** [comment] 2016-01-29 22:06
yhea, we may have to abandon the sdk. no luck on anything we've tried.  i do appreciate the help from you guys however!!!  thank you!  very responsive.

**Closed** 2016-01-29 22:24 UTC
