### ISSUE TITLE
Line Item Properties for a Product Variant

### ISSUE THREAD

**Issue by master83** [Shopify/mobile-buy-sdk-ios#426] opened 2016-11-23 19:15 UTC
Hi,

I am trying to add Line Item properties to a Product Variant in my cart, but they're not appearing on the Order Details page in admin panel for my storefront. Is there any other way I can add customer properties for every product variant I add in my cart? 

Couple of things which I have already tried are.
1. productVariant.cartLineItemsSet addObject:lineItem - where lineitem is of type BUYLineItem i.e. lineItem.properties = Dictionary
2. with BUYModelManager - lineItem = [modelManager lineItemwithVariant: productVariant] then lineItem.dictionary = Dictionary then
[self.cart.lineItemsSet addObject:lineItem]
this gives me an error for unrecognized selector
3. productVariant.optionsSet addObject:optionValueObject - optionValueObject is of type BUYOptionValue

Am I missing something or doing it wrong? All I need to do is, add custom properties for a product variant which I add in my cart.

Thanks in advance.

**Comment by davidmuzi** [comment] 2016-11-24 14:44
dupe of #423

**Closed by davidmuzi** 2016-11-24 14:44 UTC
