### ISSUE TITLE
Metafields

### ISSUE THREAD

**Issue by adanmayer** [Shopify/mobile-buy-sdk-ios#770] opened 2017-10-12 13:11 UTC
Hi, 

a good part of our product info is in metafields. Is there a way to access these from a mobile app? 
Currently this information is not available via the SDK. 

best, 
Alex.

**Comment by dbart01** [comment] 2017-10-12 13:44
There's currently no support for metafields in the SDK.

This is duplicate of #97, closing this ticket.

**Closed by dbart01** 2017-10-12 13:44 UTC
Labels: 3.x, duplicate
