### ISSUE TITLE
Filter product with low price and high price.

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#865] opened 2018-06-07 04:51 UTC
Is there any way I can Get products with price filter ?
i mean get all product with sorting of low price to high price .

**Comment by dbart01** [comment] 2018-06-07 12:45
You can sort products using the `sortKey` parameter. Filtering products within a price range is not currently supported - duplicate of #725.

**Closed by dbart01** 2018-06-07 12:45 UTC
Labels: 3.x, duplicate, enhancement
